<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Toplan\\Sms' => array($vendorDir . '/toplan/laravel-sms/src'),
    'SimpleSoftwareIO\\QrCode\\' => array($vendorDir . '/simplesoftwareio/simple-qrcode/src'),
    'Rap2hpoutre\\LaravelLogViewer\\' => array($vendorDir . '/rap2hpoutre/laravel-log-viewer/src'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'Mpociot\\ApiDoc' => array($vendorDir . '/mpociot/laravel-apidoc-generator/src'),
    'Mpociot' => array($vendorDir . '/mpociot/reflection-docblock/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Mmanos\\Search\\' => array($vendorDir . '/mmanos/laravel-search/src'),
    'Maatwebsite\\Excel\\' => array($vendorDir . '/maatwebsite/excel/src'),
    'Knp\\Snappy' => array($vendorDir . '/knplabs/knp-snappy/src'),
    'JakubOnderka\\PhpConsoleHighlighter' => array($vendorDir . '/jakub-onderka/php-console-highlighter/src'),
    'JakubOnderka\\PhpConsoleColor' => array($vendorDir . '/jakub-onderka/php-console-color/src'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Dflydev\\ApacheMimeTypes' => array($vendorDir . '/dflydev/apache-mime-types/src'),
    'Cron' => array($vendorDir . '/mtdowling/cron-expression/src'),
    'Baum' => array($vendorDir . '/baum/baum/src'),
    'Barryvdh' => array($vendorDir . '/barryvdh/reflection-docblock/src'),
    'BaconQrCode' => array($vendorDir . '/bacon/bacon-qr-code/src'),
);
